stages:
  - tests
  - allure

Run Tests:
  tags:
    - bpmgroovyRunner2
  stage: tests
  allow_failure: true
  script:
    - ./gradlew clean myTags -x test"
  artifacts:
    when: always
    paths:
      - build/allure-results

Allure report:
  stage: allure
  tags:
    - bpmgroovyRunner2
  script:
    - ./gradlew allureReport
    - echo "Allure report live here - https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/build/reports/allure-report/allureReport/index.html"
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport